Repository ikemen-engine/Ikemen-GO, pull requests merged in 2023-03, with the labels that each got.

#1041 other: Some changes to message triggers. Added Just Defended
  data/action.zss
Labels: PR: other

#1045 fix: tag.zss regression, characters not entering stage (#1043)
  data/tag.zss
Labels: PR: fix

#1047 other: Fixed typo in Just Defended
  data/action.zss
Labels: PR: other

#1056 fix: zoom affecting non-stage BG elements scaling, tension correction issues, helpers spawned with movetype A/I not being run in the same frame, pos updating/screenbound/binding 1f delay
  src/camera.go
  src/char.go
  src/stage.go
Labels: PR: fix

#1059 fix: helper remapPal during first frame of the match, omitting source/dest and assignment to -1 (#1058, #1001)
  src/bytecode.go
  src/char.go
Labels: PR: fix

#1068 fix: Fixed guarding animation lag
  data/common1.cns.zss
Labels: PR: fix

#1071 fix: getHitVar(fall.envshake.phase) default value (#1070)
  src/char.go
Labels: PR: fix

#1072 fix: hittime, hitshaketime reset if movetype != H (#1034)
  src/char.go
Labels: PR: fix

#1073 fix: fix anim scale set to 0 and defaults (#1065)
  src/anim.go
  src/common.go
Labels: PR: fix

#1074 fix: fix targetLifeAdd ignoring super.lifetodizzypointsmul and super.lifetoredlifemul (#1010)
  src/char.go
Labels: PR: fix

#1076 fix: fix redirectId in afterImage and destroySelf
  src/bytecode.go
Labels: PR: fix

#1078 fix: fix gethitvar(animtype) not returning the correct value from the start of HitDef
  src/bytecode.go
  src/char.go
Labels: PR: fix

#1080 feat: new assertSpecial flags: globalnoko, noailevel, noguardko; changed: noko, nokovelocity
  data/tag.zss
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
Labels: PR: feat

#1084 feat: new EnvShake sctrl mul parameter, HitDef envshake.mul, fall.envshake.mul, gethitvat(fall.envshake.mul)
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/stage.go
Labels: PR: feat

#1083 feat(camera): ZoomAnchor, TensionVel, Camera SCTRL
  src/bytecode.go
  src/camera.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/stage.go
Labels: PR: feat

#1085 fix: fix firstAttack trigger on counter hit
  src/bytecode.go
  src/char.go
  src/lifebar.go
  src/script.go
  src/system.go
Labels: PR: fix

#1049 feat: common files arrays, overridable by screenpack and lifebar
  src/char.go
  src/common.go
  src/compiler.go
  src/lifebar.go
  src/main.go
  src/resources/defaultConfig.json
  src/system.go
Labels: PR: feat, taget: minor

#1046 refactor: add functions.zss
  data/action.zss
  data/dizzy.zss
  data/functions.zss
  data/score.zss
  data/tag.zss
  data/training.zss
  src/resources/defaultConfig.json
Labels: PR: refactor

#1093 fix: text sctrl flicker
  src/lifebar.go
Labels: PR: fix

#1098 fix: no localcoord for redirected edge triggers
  src/bytecode.go
Labels: PR: fix

#1106 fix: OGG Files playing at 2x speed, OGG loop crash
  build/get.cmd
  build/get.sh
  go.mod
  go.sum
  src/sound.go
  src/system.go
Labels: PR: fix

#1113 feat: smaller, more readable debug ttf font
  .gitignore
  font/Open_Sans/LICENSE.txt
  font/Open_Sans/OpenSans-Bold.ttf
  font/Open_Sans/OpenSans-BoldItalic.ttf
  font/Open_Sans/OpenSans-ExtraBold.ttf
  font/Open_Sans/OpenSans-ExtraBoldItalic.ttf
  font/Open_Sans/OpenSans-Italic.ttf
  font/Open_Sans/OpenSans-Light.ttf
  font/Open_Sans/OpenSans-LightItalic.ttf
  font/Open_Sans/OpenSans-Regular.ttf
  font/Open_Sans/OpenSans-SemiBold.ttf
  font/Open_Sans/OpenSans-SemiBoldItalic.ttf
  font/debug.def
Labels: PR: feat

#1115 fix: offset+redirectId not accounting for localcoord
  src/bytecode.go
Labels: PR: fix

#1114 fix: p2 data cleared during standby, destroyself
  src/bytecode.go
  src/char.go
Labels: PR: fix

#1116 fix: bind p2 not going to state 5050 on recurring destroyself
  src/char.go
Labels: PR: fix

#1117 fix: modifyExplod remapPal
  src/bytecode.go
Labels: PR: fix

#1118 fix: Hittime frame of delay and dust generation
  src/char.go
Labels: PR: fix
