Repository ikemen-engine/Ikemen-GO, pull requests merged in 2023-05, with the labels that each got.

#1208 fix: basic actions processed after current state
  src/char.go
Labels: PR: fix

#1209 feat: spark rotation directly from Hitdef
  data/dizzy.zss
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
Labels: PR: feat

#1214 fix: make round end closer to Mugen's behavior
  src/char.go
  src/system.go
Labels: PR: fix

#1216 fix: HitOnce parameter not working for throws
  src/char.go
Labels: PR: fix

#1222 fix: regression in guarding
  src/char.go
Labels: PR: fix

#1223 fix: Explod binding with 1 frame of duration
  src/char.go
Labels: PR: fix

#1230 feat: hit and guardsound channels constants
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#1231 fix: unable to guard while paused
  src/char.go
Labels: PR: fix

#1232 other: debug keys allowed while paused
  data/training.zss
  external/script/global.lua
  src/input.go
Labels: PR: other

#1239 fix: explod updating during postype Back
  src/char.go
Labels: PR: fix

#1245 fix: Round end timing discrepancies
  src/char.go
  src/lifebar.go
  src/system.go
Labels: PR: fix

#1247 fix: Crash when AttachedChar performs the first attack, Camera View not getting reseted at the start of the round, BGM muted when getting into challenger mode
  src/bytecode.go
  src/camera.go
  src/char.go
  src/script.go
  src/system.go
Labels: PR: fix

#1248 fix: fadeout times on round end
  src/system.go
Labels: PR: fix

#1251 docs: Update README.md for build-docs links
  README.md
Labels: PR: docs

#1253 feat: EnvShake trigger
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#1254 feat: EnvShakeVar trigger
  src/bytecode.go
  src/compiler.go
  src/script.go
Labels: PR: feat
