Repository ikemen-engine/Ikemen-GO, pull requests merged in 2023-12, with the labels that each got.

#1543 other: Cache duplicated texture in glTF file
  src/stage.go
Labels: PR: other

#1546 fix: 3d stage animation
  src/stage.go
Labels: PR: fix

#1554 refactor: Corner Push, others
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
Labels: PR: refactor

#1555 fix: 3d stage animation looping fix
  src/render_gl.go
  src/stage.go
Labels: PR: fix

#1557 feat: animframe(numclsn) parameter
  src/bytecode.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#1562 feat: MoveContactFrame, GetHitFrame triggers
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#1559 fix: Red life in mixed team modes
  src/system.go
Labels: PR: fix

#1564 feat: glTF armature animation support
  src/render_gl.go
  src/shaders/model.vert.glsl
  src/stage.go
Labels: PR: feat

#1567 fix: Redirecting a PalFX clears your own
  src/bytecode.go
Labels: PR: fix

#1563 feat: SelfCommand trigger reimplementation
  src/bytecode.go
  src/compiler.go
Labels: PR: feat

#1568 fix: Explod Ownpal and common SFF's
  src/bytecode.go
  src/compiler_functions.go
Labels: PR: fix

#1570 fix: Allpalfx to trans Sub
  src/image.go
  src/render.go
  src/stage.go
Labels: PR: fix

#1571 feat: glTF Morph target animation support
  src/render_gl.go
  src/shaders/model.vert.glsl
  src/stage.go
Labels: PR: feat

#1572 feat: AssertSpecial AnimateHitpause, other fixes and refactoring
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/system.go
Labels: PR: feat

#1574 fix: default palfx for trans sub at allpalfx
  src/image.go
Labels: PR: fix
