Repository ikemen-engine/Ikemen-GO, pull requests merged in 2023-07, with the labels that each got.

#1309 fix: rewrite Explod code to improve compatibility with MUGEN 1.1
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
Labels: PR: fix

#1313 refactor: dizzy, guard, red life points
  data/common.const
  data/tag.zss
  data/training.zss
  external/script/global.lua
  src/char.go
  src/lifebar.go
  src/system.go
Labels: PR: refactor

#1316 fix: make ModifyExplod updating more like MUGEN
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
Labels: PR: fix

#1315 fix: dizzy prevention during throws
  data/dizzy.zss
Labels: PR: fix

#1318 refactor: StageBackEdgeDist and StageFrontEdgeDist
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: refactor

#1321 fix: fade screen not responding to game pausing, char turning when roundstate > 2, explod relative pos not getting set properly for ikemenver chars, persistent handling inside hitpauses
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
  src/lifebar.go
  src/system.go
Labels: PR: fix

#1323 fix: BG yDelta scrolling speed, camera getting stuck in non-4:3 ratios
  src/camera.go
  src/stage.go
Labels: PR: fix

#1327 fix: OS X systems not being able to compile GLSL shaders
  src/render_gl.go
  src/shaders/ident.frag.glsl
  src/shaders/ident.vert.glsl
  src/shaders/sprite.frag.glsl
  src/shaders/sprite.vert.glsl
Labels: PR: fix

#1332 perf: lock/unlock the speaker only if the music is going to be paused/unpaused, reduce resampling quality
  src/sound.go
Labels: PR: perf

#1333 fix: guard frame advantage
  data/training.zss
  external/script/global.lua
  src/char.go
Labels: PR: fix

#1339 fix: disabled repeating first attack score bonus
  data/score.zss
Labels: PR: fix

#1344 fix: Explicitly set GLSL shader versions
  src/render_gl.go
Labels: PR: fix

#1343 fix: HitFlag + and guarding
  src/char.go
Labels: PR: fix

#1346 fix: regression in zoom camera
  src/camera.go
  src/stage.go
Labels: PR: fix
