Repository ikemen-engine/Ikemen-GO, pull requests merged in 2023-11, with the labels that each got.

#1281 feat: powerbar multiple bg0 elements
  src/lifebar.go
Labels: PR: feat, target: minor

#1462 feat: lifebar face teammate.ko.hide
  src/lifebar.go
Labels: PR: feat, target: minor

#1470 fix: Stages bgdef mask param rgba sprites fix
  src/render.go
  src/shaders/sprite.frag.glsl
Labels: PR: fix

#1475 fix: Fixed the Ydelta on the Hires stage
  src/stage.go
Labels: PR: fix

#1480 fix: some directional input fixes
  src/compiler.go
  src/input.go
Labels: PR: fix

#1479 feat: GetHitVar(Priority), LastPlayerID, PrevStateType triggers
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#1485 feat: optionally easier inputs
  src/input.go
  src/main.go
  src/resources/defaultConfig.json
  src/system.go
Labels: PR: feat

#1486 feat: Height state controller
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
Labels: PR: feat

#1491 feat: new Height constants, ClassicPushbox option
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/input.go
  src/script.go
Labels: PR: feat

#1493 fix: persistent counters
  src/char.go
Labels: PR: fix

#1498 fix: powerbar bg0 crash
  src/lifebar.go
Labels: PR: fix

#1499 feat: ForceCrouch, HitOverride KeepState, ModifyChar
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/system.go
Labels: PR: feat

#1500 feat: easier netplay inputs
  src/input.go
  src/resources/defaultConfig.json
Labels: PR: feat

#1503 feat: JugglePoints trigger
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#1504 feat: PalFx Hue and SinHue parameters
  src/bytecode.go
  src/char.go
  src/common.go
  src/compiler_functions.go
  src/image.go
  src/render.go
  src/render_gl.go
  src/render_kinc.go
  src/script.go
  src/shaders/sprite.frag.glsl
  src/stage.go
Labels: PR: feat

#1506 feat: AnimFrame triggers
  src/bytecode.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#1509 docs: Cleanup README.md
  README.md
Labels: PR: docs

#1508 feat: AssertSpecial Immovable flag, Mugen compatibility indicator, some fixes
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/input.go
  src/lifebar.go
  src/script.go
  src/system.go
Labels: PR: feat

#1510 fix: P2Dist behavior during throws in widescreen
  src/char.go
Labels: PR: fix

#1515 fix: hitcounts were added even with Hitoverride
  src/char.go
Labels: PR: fix

#1517 refactor: version checks, minor changes
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: refactor

#1521 fix: lifebar combo updating
  src/char.go
  src/input.go
  src/lifebar.go
  src/main.go
  src/resources/defaultConfig.json
  src/system.go
Labels: PR: fix

#1522 feat: Basic glTF 3D Stage Support
  build/get.cmd
  go.mod
  go.sum
  src/camera.go
  src/render_gl.go
  src/shaders/model.frag.glsl
  src/shaders/model.vert.glsl
  src/stage.go
Labels: PR: feat

#1523 feat: Wireframe toggle for 3D stages
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#1524 fix: apply gamma correction for vertex color
  src/shaders/model.frag.glsl
Labels: PR: fix

#1525 other: glfw library
  go.mod
  go.sum
  src/input_glfw.go
  src/render_gl.go
  src/script.go
  src/system_glfw.go
Labels: PR: other

#1526 feat: 3dstage yshift parameter
  src/stage.go
Labels: PR: feat

#1528 feat: AssertCommand sctrl, MugenVersion trigger
  data/common1.cns.zss
  data/training.zss
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/input.go
  src/script.go
Labels: PR: feat

#1530 fix: Enable wireframe debug hotkey
  external/script/global.lua
Labels: PR: fix

#1535 feat: ModifyChar changing character name
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/system.go
Labels: PR: feat
