Repository ikemen-engine/Ikemen-GO, pull requests merged in 2024-11, with the labels that each got.

#2096 fix: Hitdef processing; intro skip and AIR refactoring
  src/anim.go
  src/bytecode.go
  src/char.go
  src/lifebar.go
  src/script.go
  src/system.go
Labels: PR: fix

#2095 feat: Simple Environment map, punctual light and shadow
  go.mod
  go.sum
  src/render_gl.go
  src/render_gl_darwin.go
  src/shaders/cubemapFiltering.frag.glsl
  src/shaders/model.frag.glsl
  src/shaders/model.vert.glsl
  src/shaders/panoramaToCubeMap.frag.glsl
  src/shaders/shadow.frag.glsl
  src/shaders/shadow.geo.glsl
  src/shaders/shadow.vert.glsl
  src/stage.go
Labels: PR: feat

#2098 fix:embed file name typo
  src/render_gl.go
  src/render_gl_darwin.go
Labels: PR: fix

#2099 fix: macos shader
  src/shaders/cubemapFiltering.frag.glsl
Labels: PR: fix

#2100 feat: attack/guard.dist width, height and depth
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
Labels: PR: feat

#2103 fix: attack.dist.height/proj.attack.dist.height default value
  src/char.go
Labels: PR: fix

#2105 fix:shader compilation error
  src/shaders/model.frag.glsl
Labels: PR: fix

#2107 fix:shader compilation error
  src/render_gl.go
  src/render_gl_darwin.go
  src/shaders/model.frag.glsl
Labels: PR: fix

#2110 fix: animation offset, Clsn scale, ClsnOverlap
  src/anim.go
  src/char.go
  src/common.go
  src/render.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: fix

#2109 fix: ShadowOffset SCTRL not working for X axis for shadows, -nomusic & -nosound cmd line opts
  src/anim.go
  src/char.go
  src/sound.go
Labels: PR: fix

#2112 feat:Add option to disable 3d Model and shadow
  data/system.base.def
  external/script/motif.lua
  external/script/options.lua
  src/main.go
  src/render_gl.go
  src/render_gl_darwin.go
  src/resources/defaultConfig.json
  src/script.go
  src/shaders/model.frag.glsl
  src/shaders/model.vert.glsl
  src/stage.go
  src/system.go
Labels: PR: feat

#2119 fix: 3d stage fix
  src/render_gl.go
  src/render_gl_darwin.go
  src/shaders/model.frag.glsl
  src/shaders/shadow.frag.glsl
  src/shaders/shadow.geo.glsl
  src/shaders/shadow.vert.glsl
  src/stage.go
Labels: PR: fix

#2124 feat: Separate GL 3.2 builds for Win64, Linux, and LinuxARM added to build & makefiles
  Makefile
  build/build.sh
  build/build_gl32.cmd
  external/script/start.lua
  src/compiler_functions.go
  src/input_glfw.go
  src/main.go
  src/render_gl.go
  src/render_gl_gl32.go
  src/resources/defaultConfig.json
  src/script.go
  src/system.go
  src/system_glfw.go
  src/util_desktop.go
Labels: PR: feat

#2125 refactor: drawpalno, hitflags
  data/common1.cns.zss
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/lifebar.go
  src/script.go
  src/system.go
Labels: PR: refactor

#2126 fix: gethitvar(kill)
  src/char.go
Labels: PR: fix

#2127 build: Include gl3.2 build in Windows, Linux releases
  .github/workflows/releases.yml
Labels: PR: build

#2128 fix: now uses latest glfont, fixes stage BGM playback issues when screenpack music defined
  external/script/start.lua
  go.mod
  go.sum
Labels: PR: fix

#2129 fix: helper commands on round end
  src/char.go
  src/system.go
Labels: PR: fix

#2134 refactor: rename wakegawakaranai, wakewakaLength
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/system.go
Labels: PR: refactor

#2133 feat: gethitvar guardflag and attr.flag
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#2135 refactor: deprecate gethitvar attr int
  data/common.const
  data/score.zss
  src/bytecode.go
  src/compiler.go
  src/script.go
Labels: PR: refactor

#2139 fix: 3d stage aspect ratio regression
  src/stage.go
Labels: PR: fix

#2145 fix: prevent command line from constantly trying to reopen BGM that's not found
  src/system.go
Labels: PR: fix

#2148 feat: new 3d stage feature
  src/render.go
  src/render_gl.go
  src/render_gl_gl32.go
  src/shaders/model.frag.glsl
  src/stage.go
Labels: PR: feat

#2151 fix: prevent array index OOB errors if not enough axes are found in JoystickState, added name to input_glfw.go output
  src/input.go
  src/input_glfw.go
Labels: PR: fix

#2157 fix: Default stage shadow colors
  src/stage.go
Labels: PR: fix

#2158 fix: Make sure all loading tasks are finished before round start
  src/render_gl.go
  src/render_gl_gl32.go
  src/system.go
Labels: PR: fix
