Repository ikemen-engine/Ikemen-GO, pull requests merged in 2024-07, with the labels that each got.

#1867 fix: Force `bgmfreqmul` to 1 when not specified
  src/stage.go
Labels: PR: fix

#1866 fix: StopOnGetHit, cheese icon, dust, double KO
  src/bytecode.go
  src/char.go
  src/lifebar.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: fix

#1868 feat: Resizable window, scale game to fit window
  src/render_gl.go
  src/system_glfw.go
Labels: PR: feat

#1869 feat: KeepAspect (MUGEN 1.1 feature), Y-centering to window scaling
  src/main.go
  src/resources/defaultConfig.json
  src/system.go
  src/system_glfw.go
Labels: PR: feat

#1872 feat: Added ability to customize behavior of master volume during menu pause.
  src/main.go
  src/resources/defaultConfig.json
  src/sound.go
  src/system.go
Labels: PR: feat

#1873 feat: GroundLevelOffset sctrl and GroundLevel trigger, fixes
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/system.go
Labels: PR: feat

#1877 fix: FightFX sounds not quietening during pause, snd playback now pauses
  src/sound.go
  src/system.go
Labels: PR: fix

#1882 feat: TargetAdd state controller, fixes
  data/common1.cns.zss
  data/dizzy.zss
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/system.go
Labels: PR: feat

#1895 fix: Improve window scaling behavior, fix broken shader scaling
  src/render_gl.go
Labels: PR: fix

#1899 refactor: Use gl.Finish to end frame
  src/render_gl.go
Labels: PR: refactor

#1900 fix: Fix inconsistent sound frame step behavior when BGM==err
  src/sound.go
Labels: PR: fix

#1903 feat: HelperType Projectile, hit detection and HitBy expansion
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
  src/system.go
Labels: PR: feat

#1906 feat: L and R inputs, DrawOnTop, DrawUnder, RunFirst and RunLast flags
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/input.go
Labels: PR: feat

#1907 feat: WindowScaleMode (nearest/bilinear filter toggle)
  src/main.go
  src/render_gl.go
  src/resources/defaultConfig.json
  src/system.go
Labels: PR: feat

#1909 fix: Removed motif sounds from pause list
  src/system.go
Labels: PR: fix

#1913 fix: Various window resizing-related fixes
  src/render_gl.go
  src/system_glfw.go
Labels: PR: fix

#1921 feat: ModifyHidef, ModifyProjectile, plus others
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/input.go
  src/script.go
  src/system.go
Labels: PR: feat
