Repository ikemen-engine/Ikemen-GO, pull requests merged in 2024-12, with the labels that each got.

#2161 fix: GetHitVar no-op parameter crash
  src/compiler.go
Labels: PR: fix

#2164 feat: AssertSpecial NoKoFall, MoveHitSet state controller, fixes
  data/dizzy.zss
  data/training.zss
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
Labels: PR: feat

#2167 fix: lighting not cleared in stages without punctual light
  src/stage.go
Labels: PR: fix

#2174 feat: Hitdefvar pausetimes, fixes
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/lifebar.go
  src/script.go
Labels: PR: feat

#2177 fix: GetHitVar localcoord regression
  src/char.go
Labels: PR: fix

#2179 refactor: PostProcessingShader stored as string
  external/script/options.lua
  src/main.go
  src/render_gl.go
  src/render_gl_gl32.go
  src/resources/defaultConfig.json
  src/system.go
Labels: PR: refactor

#2181 refactor: Make the backGround type enum safer
  src/stage.go
Labels: PR: refactor

#2182 fix: BGM not loading from stage directory on command line and PlayBGM SCTRL
  src/bytecode.go
  src/system.go
Labels: PR: fix

#2185 feat: separate Window Size from GameWidth/GameHeight, add WindowWidth and WindowHeight to config.json
  src/main.go
  src/resources/defaultConfig.json
  src/system.go
  src/system_glfw.go
Labels: PR: feat

#2186 fix: shadow map sampling problem
  data/system.base.def
  src/render_gl.go
  src/render_gl_gl32.go
  src/shaders/model.frag.glsl
  src/shaders/shadow.frag.glsl
  src/stage.go
Labels: PR: fix

#2191 fix: turns mode crashing with AttachedChars
  src/system.go
Labels: PR: fix

#2193 feat(gl): proper shader stacking
  src/render_gl.go
  src/render_gl_gl32.go
Labels: PR: feat

#2199 feat: mugen style config.ini, GameOption trigger
  .gitignore
  data/system.base.def
  data/system.zss
  external/script/global.lua
  external/script/main.lua
  external/script/menu.lua
  external/script/motif.lua
  external/script/options.lua
  external/script/screenpack.lua
  external/script/start.lua
  external/script/storyboard.lua
  go.mod
  go.sum
  src/bytecode.go
  src/camera.go
  src/char.go
  src/compiler.go
  src/config.go
  src/image.go
  src/iniutils.go
  src/input.go
  src/input_glfw.go
  src/lifebar.go
  src/main.go
  src/render_gl.go
  src/render_gl_gl32.go
  src/resources/defaultConfig.ini
  src/resources/defaultConfig.json
  src/script.go
  src/sound.go
  src/stage.go
  src/system.go
  src/system_glfw.go
  src/system_kinc.go
Labels: PR: feat

#2208 feat: roundRestarted, roundTime triggers
  external/script/global.lua
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/lifebar.go
  src/script.go
  src/system.go
Labels: PR: feat

#2209 feat: implement glTF KHR_animation_pointer
  src/stage.go
Labels: PR: feat

#2213 fix: crouching control, down get hit offset, AI cheating
  src/char.go
  src/common.go
  src/input.go
  src/lifebar.go
Labels: PR: fix

#2217 fix: config.ini regressions
  external/script/main.lua
  external/script/options.lua
  src/common.go
  src/config.go
  src/iniutils.go
  src/render_gl.go
  src/render_gl_gl32.go
  src/resources/defaultConfig.ini
  src/script.go
  src/system.go
Labels: PR: fix

#2223 fix: add missing const, stagevar, projvar; refactor
  external/script/main.lua
  external/script/menu.lua
  external/script/start.lua
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: fix
