Repository ikemen-engine/Ikemen-GO, pull requests merged in 2024-08, with the labels that each got.

#1931 fix: Swap & bind framebuffer when taking screenshots, skip viewport resize on window/game res being the same, add MSAA samples setting
  data/system.base.def
  external/script/motif.lua
  external/script/options.lua
  src/main.go
  src/render_gl.go
  src/resources/defaultConfig.json
  src/script.go
  src/system.go
  src/system_glfw.go
Labels: PR: fix

#1937 fix: Resolve issue with stage's reflection after language update.
  external/script/options.lua
  src/stage.go
Labels: PR: fix

#1939 fix(motif): language merging behavior
  external/script/motif.lua
Labels: PR: fix

#1946 feat: improved Char/Stage layering, fixes
  data/training.zss
  external/script/main.lua
  external/script/options.lua
  external/script/start.lua
  external/script/storyboard.lua
  src/bgdef.go
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#1947 feat: clsnVar, explodVar, projVar triggers, xAccel for hitdefs, expanded # of noChainID args
  data/common1.cns.zss
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
Labels: PR: feat

#1948 refactor: Use post-process shaders *after* resizing frame
  src/render_gl.go
Labels: PR: refactor

#1949 feat: Now uses latest Beep v2 library, audioSampleRate is now functional
  go.mod
  go.sum
  src/char.go
  src/main.go
  src/script.go
  src/sound.go
  src/system.go
Labels: PR: feat

#1952 feat: expanded AttackMulSet, fixes, refactoring
  data/dizzy.zss
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/system.go
Labels: PR: feat

#1960 fix: IsHomeTeam in Watch mode
  external/script/main.lua
Labels: PR: fix

#1961 fix: ReversalDef and SuperPause
  src/bytecode.go
  src/char.go
Labels: PR: fix

#1962 fix: 3D stage localcoord scale
  src/stage.go
Labels: PR: fix

#1964 fix: camera tracking
  src/camera.go
Labels: PR: fix

#1965 feat: NoFallHitflag AssertSpecial
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/system.go
Labels: PR: feat

#1970 fix: Credit button in VS screen
  external/script/start.lua
Labels: PR: fix

#1971 feat: NoMakeDust AssertSpecial affects MakeDust sctrl
  src/char.go
Labels: PR: feat

#1972 fix: F1 screen inputs carry to the menu
  external/script/main.lua
Labels: PR: fix

#1973 fix: Select screen character anim default values
  data/system.base.def
  external/script/motif.lua
  external/script/start.lua
Labels: PR: fix

#1974 feat: expose current time to shaders
  src/render_gl.go
  src/render_gl_darwin.go
Labels: PR: feat

#1975 feat: Added shadow and reflection offsets, made reflection a shadow, clsnVar fixes, shadow offset fixes
  src/anim.go
  src/bytecode.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#1979 fix: motif.lua nil reference
  external/script/motif.lua
Labels: PR: fix
