Repository ikemen-engine/Ikemen-GO, pull requests merged in 2024-10, with the labels that each got.

#2042 feat: Z distance triggers, refactoring, fixes
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/system.go
Labels: PR: feat

#2044 fix: remove deprecated triggers from Lua and Zss
  data/tag.zss
  external/script/main.lua
  external/script/options.lua
  external/script/start.lua
Labels: PR: fix

#2045 feat: Restored Mugen behavior to accept p3start and onward, removed p1p3dist
  src/char.go
  src/stage.go
Labels: PR: feat

#2050 feat: partnerspacing, pXfacing params
  src/char.go
  src/stage.go
Labels: PR: feat

#2053 refactor: juggling system, misc
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/font.go
  src/script.go
Labels: PR: refactor

#2055 feat: projdepthbound, Scale Z trigger; refactor: Z axis rescaling
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
Labels: PR: feat

#2060 fix: Stage window in stages with xscale and yscale
  src/stage.go
Labels: PR: fix

#2061 fix: partnerspacing, pXstartz,run.up and run.down, z boundaries
  src/char.go
  src/stage.go
Labels: PR: fix

#2058 feat: New Lua entity search methods to prepare for Lua console implementation, MConsole equivalent methods; fix: explodvar scale/angle interpolation
  external/script/global.lua
  src/char.go
  src/script.go
Labels: PR: feat

#2062 fix: debug mode triggers
  external/script/global.lua
  src/script.go
Labels: PR: fix

#2064 refactor: rename windres files and folders
  windres/README
  windres/icon-src/Cylia/IkemenCylia.png
  windres/icon-src/Cylia/ikemen.svg
  windres/icon-src/CyliaV2/IkemenCylia_V2.png
  windres/icon-src/CyliaV2/ikemen_v2.svg
  windres/icon-src/V1/16x16.png
  windres/icon-src/V1/24x24.png
  windres/icon-src/V1/256x256.png
  windres/icon-src/V1/32x32.png
  windres/icon-src/V1/48x48.png
  windres/icon-src/V1/96x96.png
  windres/icon-src/V2/16x16.png
  windres/icon-src/V2/20x20.png
  windres/icon-src/V2/24x24.png
  windres/icon-src/V2/256x256.png
  windres/icon-src/V2/32x32.png
  windres/icon-src/V2/384x384.png
  windres/icon-src/V2/4324324322.png
  windres/icon-src/V2/48x48.png
  windres/icon-src/V2/96x96.png
Labels: PR: refactor

#2066 refactor: stage localcoord, StageVar, ModifyExplod
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
  src/script.go
  src/stage.go
Labels: PR: refactor

#2067 feat: added z for hitdef params and sctrls,topEdgeDist/bottomEdgeDist triggers, fixes
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
Labels: PR: feat

#2069 fix: missing ground.velocity.z in script.go
  src/script.go
Labels: PR: fix

#2070 feat: New "LifeToPowerMul" constants, redundancy refactor, minor fixes
  data/common.const
  src/bytecode.go
  src/char.go
  src/script.go
  src/system.go
Labels: PR: feat

#2072 fix: renamed topEdgeDist/bottomEdgeDist triggers for clarity
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: fix

#2073 fix: HitVel X trigger, Hitdef power; refactor: ClsnOverlap
  src/bytecode.go
  src/char.go
  src/script.go
Labels: PR: fix

#2078 fix: explodvar scale showing 0 with no interpolation
  src/char.go
Labels: PR: fix

#2079 feat: projvar(guardflag)
  external/script/options.lua
  src/bytecode.go
  src/char.go
  src/compiler.go
Labels: PR: feat

#2082 feat: removeText, new text params, numText trigger, explod friction
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/font.go
  src/lifebar.go
  src/script.go
Labels: PR: feat

#2085 fix: minor issues
  data/dizzy.zss
  src/bytecode.go
  src/char.go
Labels: PR: fix

#2088 fix: Palette defaulting when choosing duplicates
  external/script/start.lua
Labels: PR: fix

#2091 fix: projectile localcoord yaccel, TransformClsn redirection
  src/bytecode.go
  src/char.go
Labels: PR: fix

#2092 feat: ProjVar facing trigger
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: feat
