Repository ikemen-engine/Ikemen-GO, pull requests merged in 2024-09, with the labels that each got.

#1981 feat: Added ShadowOffset SCTRL, fix: CLSNVar, ExplodVar, ProjVar LocalCoord
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/system.go
Labels: PR: feat

#1983 fix: Fixes debug logging on MacOS
  external/script/main.lua
Labels: PR: fix

#1985 feat: fight screen LocalCoord triggers, refactoring
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#1991 feat: single rounds, helper ID, projectile teamside, refactoring
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/lifebar.go
  src/system.go
Labels: PR: feat

#1998 feat: disable fight screen announcements, minor feats, refactoring
  data/training.zss
  external/script/global.lua
  external/script/main.lua
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/lifebar.go
  src/script.go
  src/system.go
Labels: PR: feat

#2000 feat: Collisions Rotation feat and Text sctr/Debug text blend mode inverse bug fix
  src/anim.go
  src/bytecode.go
  src/char.go
  src/common.go
  src/compiler_functions.go
  src/render.go
  src/render_gl.go
  src/system.go
Labels: PR: feat

#2001 fix: MacOS build crash fix
  src/render_gl_darwin.go
Labels: PR: fix

#2002 feat: TransformClsn, minor feats, refactoring, fixes
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/lifebar.go
  src/script.go
  src/system.go
Labels: PR: feat

#2006 refactor: randomtest.lua, add detailed comments
  external/script/randomtest.lua
  src/system.go
Labels: PR: refactor

#2009 feat: Preliminary Z-axis support, fix: shadow/reflection fixes, XInput fixes, BGM volume scaling
  Makefile
  build/Info.plist
  build/bundle_run.sh
  external/script/options.lua
  go.mod
  go.sum
  src/anim.go
  src/bytecode.go
  src/camera.go
  src/char.go
  src/common.go
  src/compiler.go
  src/compiler_functions.go
  src/input.go
  src/input_glfw.go
  src/main.go
  src/render.go
  src/resources/defaultConfig.json
  src/script.go
  src/sound.go
  src/stage.go
  src/system.go
Labels: PR: feat

#2011 feat: Helper OwnClsnScale, InCustomAnim, AnimPlayerNo, IkemenVersion
  data/training.zss
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#2015 feat: weight and push factor constants, more Z axis work, fixes
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
  src/stage.go
  src/system.go
Labels: PR: feat

#2018 fix: Clsn debug draw y offset bug fix, HelperIndex refactor, more cases where text blend inversing fixes
  src/bytecode.go
  src/char.go
  src/lifebar.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: fix

#2027 feat: ClsnOverlap trigger, PlayerPush priority, refactoring, fixes
  data/common.const
  data/dizzy.zss
  data/guardbreak.zss
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/input.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#2029 fix: explodVar positions, misc. sound related fixes
  src/bytecode.go
  src/char.go
  src/script.go
  src/sound.go
Labels: PR: fix

#2033 fix: Language Options: Fix a crash and changed how languages are set
  external/script/motif.lua
  external/script/options.lua
Labels: PR: fix

#2034 feat: HitDefVar trigger
  src/bytecode.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#2031 fix: size box hit detection, modify helper, revert state version check
  src/bytecode.go
  src/char.go
  src/compiler.go
Labels: PR: fix

#2035 fix: projectiles hitting multiple times in same frame
  src/char.go
Labels: PR: fix

#2036 fix: Z axis, explod crash
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
  src/system.go
Labels: PR: fix

#2038 refactor: remove framespercount, gamefps
  src/bytecode.go
  src/compiler.go
  src/script.go
Labels: PR: refactor

#2039 refactor: remove deprecated triggers
  src/bytecode.go
  src/compiler.go
  src/script.go
Labels: PR: refactor
