Repository ikemen-engine/Ikemen-GO, pull requests merged in 2024-04, with the labels that each got.

#1716 feat: LocalCoord trigger
  data/tag.zss
  src/bytecode.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#1718 fix: sparkangle regression
  src/char.go
Labels: PR: fix

#1721 fix: Fixes #1683
  src/system.go
Labels: PR: fix

#1726 feat: stage Ikemenversion and load time, several minor fixes
  src/char.go
  src/stage.go
  src/system.go
Labels: PR: feat

#1728 fix: Camera moving leftward incorrectly
  src/camera.go
Labels: PR: fix

#1730 feat: common FX localcoord, plus fixes
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/lifebar.go
  src/script.go
Labels: PR: feat

#1731 fix: incorrect horizontal camera bound
  src/camera.go
Labels: PR: fix

#1732 other: incorrect horizontal camera bound
  src/camera.go
Labels: PR: other

#1734 fix: Square shadows, semi transparent palette colors and masking fixes.
  src/anim.go
  src/render.go
  src/shaders/sprite.frag.glsl
Labels: PR: fix

#1733 fix: Pausetime trigger with Movetime
  src/bytecode.go
  src/char.go
Labels: PR: fix

#1736 fix: Initial camera zoom larger than stage's "zoomin" bound
  src/camera.go
Labels: PR: fix

#1738 fix: camera zoomindelay
  src/camera.go
Labels: PR: fix

#1739 feat: Add GameFPS trigger and display to debug.
  external/script/global.lua
  src/bytecode.go
  src/compiler.go
  src/render_gl.go
  src/script.go
  src/system.go
  src/system_glfw.go
Labels: PR: feat

#1741 refactor: Moved GameFPS to where rest of ext. triggers live
  src/bytecode.go
  src/compiler.go
  src/script.go
Labels: PR: refactor

#1740 fix: ytension zoom regression
  src/camera.go
Labels: PR: fix

#1744 feat: LifeBarVar trigger
  src/bytecode.go
  src/compiler.go
  src/lifebar.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#1748 fix: TargetBind, juggling
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: fix

#1753 fix: P2BodyDist X calculation between different localcoords
  src/char.go
  src/script.go
Labels: PR: fix

#1750 feat: Add ModifySnd SCTRL
  src/bytecode.go
  src/compiler.go
  src/compiler_functions.go
  src/sound.go
Labels: PR: feat

#1754 other: ModifySnd now allows -1 to modify all channels
  src/bytecode.go
  src/compiler_functions.go
  src/sound.go
Labels: PR: other

#1760 fix: Camera calculation fix
  src/camera.go
Labels: PR: fix

#1759 fix: commands during custom states, TicksPerSecond
  src/bytecode.go
  src/char.go
Labels: PR: fix

#1762 fix: sys.changeStateNest loop off-by-one error, added unique - state case
  src/char.go
Labels: PR: fix
