Repository ikemen-engine/Ikemen-GO, pull requests merged in 2025-07, with the labels that each got.

#2524 fix(input): Make exclusive directions exclude opposing directions.
  src/input.go
Labels: PR: fix

#2527 feat: Add MissOnOverride parameter to HitDef.
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
Labels: PR: feat

#2529 fix: Put blank recovery common command back in.
  data/common.cmd
Labels: PR: fix

#2531 feat: Command key.time parameter. Refactoring
  data/common.cmd
  data/common.const
  data/common1.cns.zss
  src/char.go
  src/compiler.go
  src/input.go
  src/resources/defaultConfig.ini
  src/script.go
Labels: PR: feat

#2544 fix: ChangeAnim2 typo; minor fixes and refactoring
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
  src/stage.go
Labels: PR: fix

#2550 other:Oops I screwed up the isclsnproxy trigger, apparently, somehow.
  src/compiler.go
Labels: PR: other

#2546 fix: Fixed HitBy/NotHitBy PlayerNo and PlayerID not working
  src/char.go
Labels: PR: fix

#2557 fix: anim/spritePlayerNo crashing unsafely and not working for explods
  src/bytecode.go
  src/compiler_functions.go
Labels: PR: fix
