Repository ikemen-engine/Ikemen-GO, pull requests merged in 2025-03, with the labels that each got.

#2345 fix: Fix the problem where stage tile x does not work properly
  src/render.go
Labels: PR: fix

#2343 feat: Helper and Target index, StageBGVar, ModifyStageBG, other
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/image.go
  src/script.go
  src/stage.go
Labels: PR: feat

#2344 feat:New screenpack parameters to load and render a glTF model
  external/script/motif.lua
  external/script/storyboard.lua
  src/bgdef.go
  src/common.go
  src/render.go
  src/render_gl.go
  src/render_gl_gl32.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#2354 fix: helper OwnClsnScale, Z pushing
  src/char.go
Labels: PR: fix

#2355 fix: ModifyStageVar now only resets the camera when camera variables are modified
  src/bytecode.go
Labels: PR: fix

#2361 feat: add ModifyBGCtrl3d to chars
  src/bytecode.go
  src/compiler.go
  src/compiler_functions.go
  src/stage.go
Labels: PR: feat

#2356 refactor: default screenpack
  src/resources/defaultConfig.ini
Labels: PR: refactor

#2363 fix: remove unnecessary inner loop in ModifyBGCtrl3D
  src/stage.go
Labels: PR: fix

#2372 fix: AttackDist, unguardable projectiles, netplay lifebars; refactoring
  external/script/global.lua
  external/script/main.lua
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/lifebar.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: fix

#2375 feat: DrawPal trigger
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: feat

#2376 refactor: swap bgNew arguments
  external/script/motif.lua
  external/script/storyboard.lua
  src/script.go
Labels: PR: refactor

#2378 fix: drawPal trigger
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/script.go
Labels: PR: fix

#2379 fix: select.def musicvictory parameter not working, drawPal error messages
  external/script/start.lua
  src/compiler.go
Labels: PR: fix

#2384 feat: NumStageBG trigger; fix lost camera; error and other refactors
  src/bytecode.go
  src/char.go
  src/common.go
  src/compiler.go
  src/compiler_functions.go
  src/main.go
  src/script.go
  src/system.go
Labels: PR: feat

#2383 fix: incorrect model tangent
  src/render_gl.go
  src/render_gl_gl32.go
Labels: PR: fix

#2388 feat: window sctrl, window param for shadows/reflections, modifyShadow/reflection; fixes
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/stage.go
Labels: PR: feat

#2395 fix: revert HitDef WinMugen compatibility refactor
  src/bytecode.go
  src/char.go
Labels: PR: fix
