Repository ikemen-engine/Ikemen-GO, pull requests merged in 2025-09, with the labels that each got.

#2612 feat(motif): per player cursor.tween ;syntax fix
  data/system.base.def
  external/script/motif.lua
  external/script/start.lua
Labels: PR: feat

#2616 feat(sctrl): ShiftInput; fixes; refactor
  data/common.const
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/input.go
  src/script.go
  src/system.go
Labels: PR: feat

#2618 fix: Immediate BGM RAM swap after load instead of waiting for margin …
  src/sound.go
Labels: PR: fix

#2620 fix: Shaders now allowed from appbundle for macOS, executable path is now retrieved only once
  src/system.go
Labels: PR: fix

#2623 fix: lifebar windows inconsistent between 4:3 and 16:9
  src/common.go
Labels: PR: fix

#2627 build: arenas env var
  .github/workflows/releases.yml
Labels: PR: build

#2630 feat: Made BGM RAM Swap a toggleable feature; fix: possible deadlock in SwapSeeker; build fixes
  Makefile
  build/build.sh
  build/bundle_run.sh
  src/config.go
  src/resources/defaultConfig.ini
  src/sound.go
Labels: PR: feat

#2631 fix: Char animBackup causing crashes on rollback during superpauses
  src/state_clone.go
Labels: PR: fix

#2639 build: fix appbundle for macOS (hopefully for good)
  .github/workflows/releases.yml
  Makefile
Labels: PR: build

#2640 fix(rollback): command desyncs, Tag inputs; refactor: less code duplication
  src/char.go
  src/net.go
  src/resources/defaultConfig.ini
  src/rollback.go
  src/script.go
  src/state.go
  src/state_clone.go
  src/system.go
Labels: PR: fix

#2641 build: fix missing space required for if statement to correctly fire
  .github/workflows/releases.yml
Labels: PR: build

#2642 fix: macos make app command
  .github/workflows/releases.yml
Labels: PR: fix

#2654 fix: Fixed parallax in stages so that scalestart affects the X-coordinate
  src/char.go
  src/compiler_functions.go
  src/sound.go
  src/stage.go
Labels: PR: fix

#2662 fix: regressions; refactor: explods
  src/bytecode.go
  src/char.go
  src/common.go
  src/net.go
  src/stage.go
  src/system.go
Labels: PR: fix

#2669 fix: certain characters not being able to have their alts when selected
  external/script/start.lua
Labels: PR: fix

#2672 fix: rollback desync, SuperPause effects, explod regressions; refactoring
  external/script/main.lua
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
  src/config.go
  src/image.go
  src/input.go
  src/lifebar.go
  src/net.go
  src/resources/defaultConfig.ini
  src/rollback.go
  src/script.go
  src/state.go
  src/state_clone.go
  src/system.go
Labels: PR: fix

#2674 feat: add support for prefixes in lifebarActions
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
Labels: PR: feat

#2676 fix: explods, intro sounds, ">" inputs; refactor: SystemVar renamed GameVar
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/input.go
  src/script.go
  src/system.go
Labels: PR: fix

#2689 build: respect BUILD_FFMPEG=yes
  build/build.sh
Labels: PR: build

#2691 fix: FFmpeg 7.1 and 8.0 support
  .github/workflows/releases.yml
  build/build.sh
  go.mod
  go.sum
  src/video_ffmpeg.go
Labels: PR: fix

#2694 feat: Video loop
  go.mod
  go.sum
  src/stage.go
  src/video_ffmpeg.go
Labels: PR: feat

#2698 fix: Video respecting pause and visible/enable BGCtrl
  src/bgdef.go
  src/stage.go
  src/video_ffmpeg.go
Labels: PR: fix

#2707 fix: NotHitBy regression
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
Labels: PR: fix

#2716 fix: video stage rendering, scalemode coordinate space
  go.mod
  go.sum
  src/anim.go
  src/common.go
  src/stage.go
  src/video_ffmpeg.go
Labels: PR: fix

#2718 fix: video loop video stream speed up
  src/video_ffmpeg.go
Labels: PR: fix

#2725 refactor: remove redudant tween toggle
  .gitattributes
  build/build.sh
  data/system.base.def
  external/script/main.lua
  external/script/motif.lua
Labels: PR: refactor

#2724 feat: Add new ModifyPlayer parameters
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/system.go
Labels: PR: feat
