Repository ikemen-engine/Ikemen-GO, pull requests merged in 2025-04, with the labels that each got.

#2400 feat: TransformSprite, xshear for explods & projectiles, angle & xshear for BG Elements; fixes
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#2401 refactor: Clsn, hit detection
  src/anim.go
  src/bytecode.go
  src/char.go
  src/script.go
  src/system.go
Labels: PR: refactor

#2403 feat: View frustum culling
  src/bgdef.go
  src/stage.go
Labels: PR: feat

#2404 fix: st file "out of bounds"; minor refactors
  src/char.go
  src/common.go
  src/render.go
  src/resources/defaultConfig.ini
Labels: PR: fix

#2406 fix: modifyshadow and modifyreflection, xshear fliping sides with angleDraw; refactor
  src/anim.go
  src/bytecode.go
  src/char.go
  src/script.go
  src/system.go
Labels: PR: fix

#2409 feat: "unlimited" variables, IsHelper index; refactoring
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/system.go
Labels: PR: feat

#2412 refactor: 3d model rendering optimization
  src/render_gl.go
  src/render_gl_gl32.go
  src/stage.go
Labels: PR: refactor

#2416 feat: time for ExplodVar, fix: SoundVar channel -1 not working properly
  src/bytecode.go
  src/char.go
  src/compiler.go
Labels: PR: feat

#2430 feat: ProjVar time; Tag refactoring; other fixes
  data/action.zss
  data/dizzy.zss
  data/functions.zss
  data/guardbreak.zss
  data/score.zss
  data/tag.zss
  data/training.zss
  src/anim.go
  src/bytecode.go
  src/char.go
  src/common.go
  src/compiler.go
  src/input.go
  src/script.go
Labels: PR: feat

#2436 feat: AssertSpecial "enabled" parameter; fixes
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler_functions.go
Labels: PR: feat

#2438 feat: envshake dir parameter
  src/anim.go
  src/bytecode.go
  src/char.go
  src/compiler.go
  src/compiler_functions.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#2437 feat: new lifebar and text sctrl features; fix
  src/anim.go
  src/bytecode.go
  src/char.go
  src/common.go
  src/compiler.go
  src/compiler_functions.go
  src/font.go
  src/image.go
  src/lifebar.go
  src/script.go
  src/stage.go
  src/system.go
Labels: PR: feat

#2440 fix: lifebar elements xshear offset, timer counter, combo bg0 and top default layerno
  src/common.go
  src/font.go
  src/lifebar.go
Labels: PR: fix

#2439 fix: attached char enemies
  src/char.go
  src/common.go
Labels: PR: fix
